### ISSUE TITLE
Crash when not selecting a colour

### ISSUE THREAD

**Issue by MegaDood11** [Sambo3975/SMBX2-Tileset-Creator#2] opened 2021-05-23 07:42 UTC
**Describe the bug**

**To Reproduce**
1. Open an image
2. Click on 'Select Color'
3. Click 'Cancel' or exit out of the window

**Expected behavior**
Expected to close the 'Select Color' window and retain the currently selected colour.

**Error Traceback**
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1885, in __call__
  File "widgets.py", line 24, in load_color_data
  File "tkinter\__init__.py", line 1639, in configure
  File "tkinter\__init__.py", line 1629, in _configure
_tkinter.TclError: unknown color name "None"

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Sambo3975** [comment] 2021-05-23 15:32
Closed as this is a duplicate of #1

**Closed as completed by Sambo3975** 2021-05-23 15:32 UTC
Labels: duplicate
