### ISSUE TITLE
Selecting a tile and changing pixel scale causes a crash

### ISSUE THREAD

**Issue by MegaDood11** [Sambo3975/SMBX2-Tileset-Creator#16] opened 2021-06-14 04:58 UTC
**Describe the bug**
Selecting a grid space to create a tile, and editing the Pixel Scale while there are selected tiles causes the Importer to crash

**To Reproduce**
1. Open an image
2. Click on a gridspace to create a block/bgo
3. Change the pixel scale while there's at least one selected gridspace

**Expected behavior**
Expected the gridspaces to change in scale to fit the newly adjusted pixel scale as well as the image

**Error Traceback**

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1885, in __call__
  File "main.py", line 889, in redraw_canvas
  File "main.py", line 813, in _redraw_tiles
  File "tile.py", line 291, in redraw
  File "tile.py", line 220, in set_scale
  File "tile.py", line 210, in _scale_grid_settings
TypeError: unsupported operand type(s) for //: 'list' and 'int'

**Desktop (please complete the following information):**
 Windows 10

**Additional context**
Seems to work with any image, regardless of image size.

**Comment by Sambo3975** [comment] 2021-06-14 18:10
There are a couple things that could be wrong:
1. You have an outdated version. The traceback makes it look like this is the case, as it is identical to the one from a bug report made before the hotfix was released.
2. Your `.tileset.ini` file was created in an older version, and the new version doesn't like the data in the old file. This seems less likely, as when I test this case on my machine, the error message is from the same line but says something different from yours. Regardless, this is an issue that needs to be fixed.

Please provide the `.png` and the `.tileset.json` files with which you are experiencing this error. The `.tileset.json` file should be in the same folder as your `.png`, and it should have the same name as the `.png`. This will make it so I know which of the above cases we're dealing with.

**Comment by Sambo3975** [comment] 2021-06-14 18:12
Item 2 has been fixed in the next version.

**Comment by Sambo3975** [comment] 2021-06-15 04:20
Closed because the related bug has been fixed. The newest release should resolve your problem. If it doesn't, feel free to reopen this issue.

**Closed as completed by Sambo3975** 2021-06-15 04:20 UTC
Labels: bug

**Comment by Alucard648** [comment] 2021-06-15 04:58
Bugfix confirmed.
